# Generated by Django 4.2.7 on 2024-01-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='arquivo',
            field=models.ImageField(blank=True, null=True, upload_to='arquivos/'),
        ),
    ]
