# Generated by Django 4.2.7 on 2024-01-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_productmodel_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
