# Generated by Django 4.2.7 on 2024-01-25 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_productmodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'permissions': [('view_category', 'Pode visualizar categoria'), ('change_category', 'Pode criar/editar categoria'), ('delete_category', 'Pode eliminar categoria')]},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'permissions': [('view_product', 'Pode visualizar producto'), ('change_product', 'Pode criar/editar producto'), ('delete_product', 'Pode eliminar producto')]},
        ),
        migrations.AlterModelOptions(
            name='taxmodel',
            options={'permissions': [('view_tax', 'Pode visualizar imposto'), ('change_tax', 'Pode criar/editar imposto'), ('delete_tax', 'Pode eliminar imposto')]},
        ),
    ]
