# Generated by Django 4.2.7 on 2024-02-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_categorymodel_saved_by_productmodel_saved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('how_many_number', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'permissions': [('view_reserve', 'Pode visualizar reserva'), ('change_reserve', 'Pode criar/editar reserva'), ('delete_reserve', 'Pode eliminar reserva')],
            },
        ),
    ]
