# Generated by Django 4.2.7 on 2024-01-25 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customermodel',
            options={'permissions': [('view_customer', 'Pode visualizar cliente'), ('change_customer', 'Pode criar/editar cliente'), ('delete_customer', 'Pode eliminar cliente')]},
        ),
    ]
