# Generated by Django 4.2.7 on 2024-01-25 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'permissions': [('view_position', 'Pode visualizar Cargo/Função'), ('change_position', 'Pode criar/editar Cargo/Função'), ('delete_position', 'Pode eliminar Cargo/Função')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, default=25000, max_digits=12)),
                ('email', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.positionmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('view_employee', 'Pode visualizar Funcionário'), ('change_employee', 'Pode criar/editar Funcionário'), ('delete_employee', 'Pode eliminar Funcionário')],
            },
        ),
    ]
